#!/bin/sh

# Run RuboCop on staged Ruby files
STAGED_RUBY_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rb$')

if [ -n "$STAGED_RUBY_FILES" ]; then
  echo "$STAGED_RUBY_FILES" | xargs bundle exec rubocop --force-exclusion
else
  exit 0
fi


# Exit with error if RuboCop finds issues
if [ $? -ne 0 ]; then
  echo "RuboCop found offenses, commit aborted!"
  exit 1
fi